/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountResetApiKey } from "../../funcs/accountResetApiKey.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$accountResetApiKey: ToolDefinition = {
  name: "account-reset-api-key",
  description: `Reset team API key

Reset the API key for the authenticated team. This will invalidate the current API key and generate a new one.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await accountResetApiKey(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
