/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountUpdateProfile } from "../../funcs/accountUpdateProfile.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PutApiAccountProfileRequest$inboundSchema,
};

export const tool$accountUpdateProfile: ToolDefinition<typeof args> = {
  name: "account-update-profile",
  description: `Update team profile

Update profile information for the authenticated team`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await accountUpdateProfile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
