/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminTeamsReactivate } from "../../funcs/adminTeamsReactivate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiAdminTeamsTeamIdReactivateRequest$inboundSchema,
};

export const tool$adminTeamsReactivate: ToolDefinition<typeof args> = {
  name: "admin-teams-reactivate",
  description: `Reactivate a team

Reactivate a previously deactivated team, allowing them to participate in the competition again.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await adminTeamsReactivate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
