/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { competitionGetStatus } from "../../funcs/competitionGetStatus.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$competitionGetStatus: ToolDefinition = {
  name: "competition-get-status",
  description: `Get competition status

Get the status of the active competition`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await competitionGetStatus(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
