/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { priceGet } from "../../funcs/priceGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiPriceRequest$inboundSchema,
};

export const tool$priceGet: ToolDefinition<typeof args> = {
  name: "price-get",
  description: `Get price for a token

Get the current price of a specified token`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await priceGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
