/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tradeExecute } from "../../funcs/tradeExecute.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiTradeExecuteRequest$inboundSchema,
};

export const tool$tradeExecute: ToolDefinition<typeof args> = {
  name: "trade-execute",
  description: `Execute a trade

Execute a trade between two tokens`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tradeExecute(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
