"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LibValidatorSet__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "validator",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "newPower",
                type: "uint256",
            },
        ],
        name: "ActiveValidatorCollateralUpdated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "validator",
                type: "address",
            },
        ],
        name: "ActiveValidatorLeft",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "oldValidator",
                type: "address",
            },
            {
                indexed: false,
                internalType: "address",
                name: "newValidator",
                type: "address",
            },
        ],
        name: "ActiveValidatorReplaced",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "validator",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "power",
                type: "uint256",
            },
        ],
        name: "NewActiveValidator",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "validator",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "power",
                type: "uint256",
            },
        ],
        name: "NewWaitingValidator",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "validator",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "newPower",
                type: "uint256",
            },
        ],
        name: "WaitingValidatorCollateralUpdated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "validator",
                type: "address",
            },
        ],
        name: "WaitingValidatorLeft",
        type: "event",
    },
];
const _bytecode = "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212204c21fbdbd4248197426c18d09b29f814a4737a2a2a7acb493eee9330e0c2aee264736f6c63430008170033";
const isSuperArgs = (xs) => xs.length > 1;
class LibValidatorSet__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    connect(runner) {
        return super.connect(runner);
    }
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.LibValidatorSet__factory = LibValidatorSet__factory;
LibValidatorSet__factory.bytecode = _bytecode;
LibValidatorSet__factory.abi = _abi;
//# sourceMappingURL=LibValidatorSet__factory.js.map