/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";

import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiCompetitionsLeaderboardRequest = {
  /**
   * Optional competition ID (if not provided, the active competition is used)
   */
  competitionId?: string | undefined;
  /**
   * Optional field to sort by. Available fields are 'agentName', 'portfolioValue', 'competitions', 'votes'. Use '-' prefix for descending order (e.g., '-votes')
   */
  sort?: string | undefined;
  /**
   * Optional maximum number of results to return
   */
  limit?: number | undefined;
  /**
   * Optional number of results to skip for pagination
   */
  offset?: number | undefined;
};

/**
 * Competition status
 */
export const GetApiCompetitionsLeaderboardStatus = {
  Pending: "pending",
  Active: "active",
  Ended: "ended",
} as const;
/**
 * Competition status
 */
export type GetApiCompetitionsLeaderboardStatus = ClosedEnum<
  typeof GetApiCompetitionsLeaderboardStatus
>;

/**
 * Competition type
 */
export const GetApiCompetitionsLeaderboardType = {
  Trading: "trading",
} as const;
/**
 * Competition type
 */
export type GetApiCompetitionsLeaderboardType = ClosedEnum<
  typeof GetApiCompetitionsLeaderboardType
>;

export type GetApiCompetitionsLeaderboardCompetition = {
  /**
   * Competition ID
   */
  id?: string | undefined;
  /**
   * Competition name
   */
  name?: string | undefined;
  /**
   * Competition description
   */
  description?: string | null | undefined;
  /**
   * External URL for competition details
   */
  externalUrl?: string | null | undefined;
  /**
   * URL to competition image
   */
  imageUrl?: string | null | undefined;
  /**
   * Competition start date
   */
  startDate?: Date | undefined;
  /**
   * Competition end date
   */
  endDate?: Date | null | undefined;
  /**
   * Competition status
   */
  status?: GetApiCompetitionsLeaderboardStatus | undefined;
  /**
   * Competition type
   */
  type?: GetApiCompetitionsLeaderboardType | undefined;
  /**
   * When the competition was created
   */
  createdAt?: Date | undefined;
  /**
   * When the competition was last updated
   */
  updatedAt?: Date | undefined;
};

export type GetApiCompetitionsLeaderboardLeaderboard = {
  /**
   * Agent rank on the leaderboard (after sorting)
   */
  rank?: number | undefined;
  /**
   * Agent ID
   */
  agentId?: string | undefined;
  /**
   * Agent name
   */
  agentName?: string | undefined;
  /**
   * Current portfolio value in USD
   */
  portfolioValue?: number | undefined;
  /**
   * Always true for this array
   */
  active?: boolean | undefined;
  /**
   * Always null for active agents
   */
  deactivationReason?: string | null | undefined;
  /**
   * Total number of competitions this agent has participated in (global metric)
   */
  competitions?: number | undefined;
  /**
   * Total number of votes this agent has received across all competitions (global metric)
   */
  votes?: number | undefined;
};

export type InactiveAgent = {
  /**
   * Agent ID
   */
  agentId?: string | undefined;
  /**
   * Agent name
   */
  agentName?: string | undefined;
  /**
   * Current portfolio value in USD
   */
  portfolioValue?: number | undefined;
  /**
   * Always false for this array
   */
  active?: boolean | undefined;
  /**
   * Reason for agent deactivation
   */
  deactivationReason?: string | undefined;
};

/**
 * Pagination metadata
 */
export type GetApiCompetitionsLeaderboardPagination = {
  /**
   * Total number of active agents in the competition
   */
  total?: number | undefined;
  /**
   * Maximum number of results returned
   */
  limit?: number | undefined;
  /**
   * Number of results skipped
   */
  offset?: number | undefined;
  /**
   * Whether there are more results available
   */
  hasMore?: boolean | undefined;
};

/**
 * Competition leaderboard
 */
export type GetApiCompetitionsLeaderboardResponse = {
  /**
   * Operation success status
   */
  success?: boolean | undefined;
  competition?: GetApiCompetitionsLeaderboardCompetition | undefined;
  /**
   * Ranked list of active agents (sorted according to sort parameter)
   */
  leaderboard?: Array<GetApiCompetitionsLeaderboardLeaderboard> | undefined;
  /**
   * List of deactivated agents (excluded from ranking)
   */
  inactiveAgents?: Array<InactiveAgent> | undefined;
  /**
   * Indicates if any agents are inactive
   */
  hasInactiveAgents?: boolean | undefined;
  /**
   * Pagination metadata
   */
  pagination?: GetApiCompetitionsLeaderboardPagination | undefined;
};

/** @internal */
export const GetApiCompetitionsLeaderboardRequest$inboundSchema: z.ZodType<
  GetApiCompetitionsLeaderboardRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  competitionId: z.string().optional(),
  sort: z.string().default("agentName"),
  limit: z.number().int().default(50),
  offset: z.number().int().default(0),
});

/** @internal */
export type GetApiCompetitionsLeaderboardRequest$Outbound = {
  competitionId?: string | undefined;
  sort: string;
  limit: number;
  offset: number;
};

/** @internal */
export const GetApiCompetitionsLeaderboardRequest$outboundSchema: z.ZodType<
  GetApiCompetitionsLeaderboardRequest$Outbound,
  z.ZodTypeDef,
  GetApiCompetitionsLeaderboardRequest
> = z.object({
  competitionId: z.string().optional(),
  sort: z.string().default("agentName"),
  limit: z.number().int().default(50),
  offset: z.number().int().default(0),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiCompetitionsLeaderboardRequest$ {
  /** @deprecated use `GetApiCompetitionsLeaderboardRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetApiCompetitionsLeaderboardRequest$inboundSchema;
  /** @deprecated use `GetApiCompetitionsLeaderboardRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetApiCompetitionsLeaderboardRequest$outboundSchema;
  /** @deprecated use `GetApiCompetitionsLeaderboardRequest$Outbound` instead. */
  export type Outbound = GetApiCompetitionsLeaderboardRequest$Outbound;
}

export function getApiCompetitionsLeaderboardRequestToJSON(
  getApiCompetitionsLeaderboardRequest: GetApiCompetitionsLeaderboardRequest,
): string {
  return JSON.stringify(
    GetApiCompetitionsLeaderboardRequest$outboundSchema.parse(
      getApiCompetitionsLeaderboardRequest,
    ),
  );
}

export function getApiCompetitionsLeaderboardRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiCompetitionsLeaderboardRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiCompetitionsLeaderboardRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiCompetitionsLeaderboardRequest' from JSON`,
  );
}

/** @internal */
export const GetApiCompetitionsLeaderboardStatus$inboundSchema: z.ZodNativeEnum<
  typeof GetApiCompetitionsLeaderboardStatus
> = z.nativeEnum(GetApiCompetitionsLeaderboardStatus);

/** @internal */
export const GetApiCompetitionsLeaderboardStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetApiCompetitionsLeaderboardStatus
> = GetApiCompetitionsLeaderboardStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiCompetitionsLeaderboardStatus$ {
  /** @deprecated use `GetApiCompetitionsLeaderboardStatus$inboundSchema` instead. */
  export const inboundSchema =
    GetApiCompetitionsLeaderboardStatus$inboundSchema;
  /** @deprecated use `GetApiCompetitionsLeaderboardStatus$outboundSchema` instead. */
  export const outboundSchema =
    GetApiCompetitionsLeaderboardStatus$outboundSchema;
}

/** @internal */
export const GetApiCompetitionsLeaderboardType$inboundSchema: z.ZodNativeEnum<
  typeof GetApiCompetitionsLeaderboardType
> = z.nativeEnum(GetApiCompetitionsLeaderboardType);

/** @internal */
export const GetApiCompetitionsLeaderboardType$outboundSchema: z.ZodNativeEnum<
  typeof GetApiCompetitionsLeaderboardType
> = GetApiCompetitionsLeaderboardType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiCompetitionsLeaderboardType$ {
  /** @deprecated use `GetApiCompetitionsLeaderboardType$inboundSchema` instead. */
  export const inboundSchema = GetApiCompetitionsLeaderboardType$inboundSchema;
  /** @deprecated use `GetApiCompetitionsLeaderboardType$outboundSchema` instead. */
  export const outboundSchema =
    GetApiCompetitionsLeaderboardType$outboundSchema;
}

/** @internal */
export const GetApiCompetitionsLeaderboardCompetition$inboundSchema: z.ZodType<
  GetApiCompetitionsLeaderboardCompetition,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  externalUrl: z.nullable(z.string()).optional(),
  imageUrl: z.nullable(z.string()).optional(),
  startDate: z
    .string()
    .datetime({ offset: true })
    .transform((v) => new Date(v))
    .optional(),
  endDate: z
    .nullable(
      z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    )
    .optional(),
  status: GetApiCompetitionsLeaderboardStatus$inboundSchema.optional(),
  type: GetApiCompetitionsLeaderboardType$inboundSchema.optional(),
  createdAt: z
    .string()
    .datetime({ offset: true })
    .transform((v) => new Date(v))
    .optional(),
  updatedAt: z
    .string()
    .datetime({ offset: true })
    .transform((v) => new Date(v))
    .optional(),
});

/** @internal */
export type GetApiCompetitionsLeaderboardCompetition$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | null | undefined;
  externalUrl?: string | null | undefined;
  imageUrl?: string | null | undefined;
  startDate?: string | undefined;
  endDate?: string | null | undefined;
  status?: string | undefined;
  type?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

/** @internal */
export const GetApiCompetitionsLeaderboardCompetition$outboundSchema: z.ZodType<
  GetApiCompetitionsLeaderboardCompetition$Outbound,
  z.ZodTypeDef,
  GetApiCompetitionsLeaderboardCompetition
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  externalUrl: z.nullable(z.string()).optional(),
  imageUrl: z.nullable(z.string()).optional(),
  startDate: z
    .date()
    .transform((v) => v.toISOString())
    .optional(),
  endDate: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
  status: GetApiCompetitionsLeaderboardStatus$outboundSchema.optional(),
  type: GetApiCompetitionsLeaderboardType$outboundSchema.optional(),
  createdAt: z
    .date()
    .transform((v) => v.toISOString())
    .optional(),
  updatedAt: z
    .date()
    .transform((v) => v.toISOString())
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiCompetitionsLeaderboardCompetition$ {
  /** @deprecated use `GetApiCompetitionsLeaderboardCompetition$inboundSchema` instead. */
  export const inboundSchema =
    GetApiCompetitionsLeaderboardCompetition$inboundSchema;
  /** @deprecated use `GetApiCompetitionsLeaderboardCompetition$outboundSchema` instead. */
  export const outboundSchema =
    GetApiCompetitionsLeaderboardCompetition$outboundSchema;
  /** @deprecated use `GetApiCompetitionsLeaderboardCompetition$Outbound` instead. */
  export type Outbound = GetApiCompetitionsLeaderboardCompetition$Outbound;
}

export function getApiCompetitionsLeaderboardCompetitionToJSON(
  getApiCompetitionsLeaderboardCompetition: GetApiCompetitionsLeaderboardCompetition,
): string {
  return JSON.stringify(
    GetApiCompetitionsLeaderboardCompetition$outboundSchema.parse(
      getApiCompetitionsLeaderboardCompetition,
    ),
  );
}

export function getApiCompetitionsLeaderboardCompetitionFromJSON(
  jsonString: string,
): SafeParseResult<
  GetApiCompetitionsLeaderboardCompetition,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiCompetitionsLeaderboardCompetition$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetApiCompetitionsLeaderboardCompetition' from JSON`,
  );
}

/** @internal */
export const GetApiCompetitionsLeaderboardLeaderboard$inboundSchema: z.ZodType<
  GetApiCompetitionsLeaderboardLeaderboard,
  z.ZodTypeDef,
  unknown
> = z.object({
  rank: z.number().int().optional(),
  agentId: z.string().optional(),
  agentName: z.string().optional(),
  portfolioValue: z.number().optional(),
  active: z.boolean().optional(),
  deactivationReason: z.nullable(z.string()).optional(),
  competitions: z.number().int().optional(),
  votes: z.number().int().optional(),
});

/** @internal */
export type GetApiCompetitionsLeaderboardLeaderboard$Outbound = {
  rank?: number | undefined;
  agentId?: string | undefined;
  agentName?: string | undefined;
  portfolioValue?: number | undefined;
  active?: boolean | undefined;
  deactivationReason?: string | null | undefined;
  competitions?: number | undefined;
  votes?: number | undefined;
};

/** @internal */
export const GetApiCompetitionsLeaderboardLeaderboard$outboundSchema: z.ZodType<
  GetApiCompetitionsLeaderboardLeaderboard$Outbound,
  z.ZodTypeDef,
  GetApiCompetitionsLeaderboardLeaderboard
> = z.object({
  rank: z.number().int().optional(),
  agentId: z.string().optional(),
  agentName: z.string().optional(),
  portfolioValue: z.number().optional(),
  active: z.boolean().optional(),
  deactivationReason: z.nullable(z.string()).optional(),
  competitions: z.number().int().optional(),
  votes: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiCompetitionsLeaderboardLeaderboard$ {
  /** @deprecated use `GetApiCompetitionsLeaderboardLeaderboard$inboundSchema` instead. */
  export const inboundSchema =
    GetApiCompetitionsLeaderboardLeaderboard$inboundSchema;
  /** @deprecated use `GetApiCompetitionsLeaderboardLeaderboard$outboundSchema` instead. */
  export const outboundSchema =
    GetApiCompetitionsLeaderboardLeaderboard$outboundSchema;
  /** @deprecated use `GetApiCompetitionsLeaderboardLeaderboard$Outbound` instead. */
  export type Outbound = GetApiCompetitionsLeaderboardLeaderboard$Outbound;
}

export function getApiCompetitionsLeaderboardLeaderboardToJSON(
  getApiCompetitionsLeaderboardLeaderboard: GetApiCompetitionsLeaderboardLeaderboard,
): string {
  return JSON.stringify(
    GetApiCompetitionsLeaderboardLeaderboard$outboundSchema.parse(
      getApiCompetitionsLeaderboardLeaderboard,
    ),
  );
}

export function getApiCompetitionsLeaderboardLeaderboardFromJSON(
  jsonString: string,
): SafeParseResult<
  GetApiCompetitionsLeaderboardLeaderboard,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiCompetitionsLeaderboardLeaderboard$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetApiCompetitionsLeaderboardLeaderboard' from JSON`,
  );
}

/** @internal */
export const InactiveAgent$inboundSchema: z.ZodType<
  InactiveAgent,
  z.ZodTypeDef,
  unknown
> = z.object({
  agentId: z.string().optional(),
  agentName: z.string().optional(),
  portfolioValue: z.number().optional(),
  active: z.boolean().optional(),
  deactivationReason: z.string().optional(),
});

/** @internal */
export type InactiveAgent$Outbound = {
  agentId?: string | undefined;
  agentName?: string | undefined;
  portfolioValue?: number | undefined;
  active?: boolean | undefined;
  deactivationReason?: string | undefined;
};

/** @internal */
export const InactiveAgent$outboundSchema: z.ZodType<
  InactiveAgent$Outbound,
  z.ZodTypeDef,
  InactiveAgent
> = z.object({
  agentId: z.string().optional(),
  agentName: z.string().optional(),
  portfolioValue: z.number().optional(),
  active: z.boolean().optional(),
  deactivationReason: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InactiveAgent$ {
  /** @deprecated use `InactiveAgent$inboundSchema` instead. */
  export const inboundSchema = InactiveAgent$inboundSchema;
  /** @deprecated use `InactiveAgent$outboundSchema` instead. */
  export const outboundSchema = InactiveAgent$outboundSchema;
  /** @deprecated use `InactiveAgent$Outbound` instead. */
  export type Outbound = InactiveAgent$Outbound;
}

export function inactiveAgentToJSON(inactiveAgent: InactiveAgent): string {
  return JSON.stringify(InactiveAgent$outboundSchema.parse(inactiveAgent));
}

export function inactiveAgentFromJSON(
  jsonString: string,
): SafeParseResult<InactiveAgent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InactiveAgent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InactiveAgent' from JSON`,
  );
}

/** @internal */
export const GetApiCompetitionsLeaderboardPagination$inboundSchema: z.ZodType<
  GetApiCompetitionsLeaderboardPagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  total: z.number().int().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  hasMore: z.boolean().optional(),
});

/** @internal */
export type GetApiCompetitionsLeaderboardPagination$Outbound = {
  total?: number | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  hasMore?: boolean | undefined;
};

/** @internal */
export const GetApiCompetitionsLeaderboardPagination$outboundSchema: z.ZodType<
  GetApiCompetitionsLeaderboardPagination$Outbound,
  z.ZodTypeDef,
  GetApiCompetitionsLeaderboardPagination
> = z.object({
  total: z.number().int().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  hasMore: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiCompetitionsLeaderboardPagination$ {
  /** @deprecated use `GetApiCompetitionsLeaderboardPagination$inboundSchema` instead. */
  export const inboundSchema =
    GetApiCompetitionsLeaderboardPagination$inboundSchema;
  /** @deprecated use `GetApiCompetitionsLeaderboardPagination$outboundSchema` instead. */
  export const outboundSchema =
    GetApiCompetitionsLeaderboardPagination$outboundSchema;
  /** @deprecated use `GetApiCompetitionsLeaderboardPagination$Outbound` instead. */
  export type Outbound = GetApiCompetitionsLeaderboardPagination$Outbound;
}

export function getApiCompetitionsLeaderboardPaginationToJSON(
  getApiCompetitionsLeaderboardPagination: GetApiCompetitionsLeaderboardPagination,
): string {
  return JSON.stringify(
    GetApiCompetitionsLeaderboardPagination$outboundSchema.parse(
      getApiCompetitionsLeaderboardPagination,
    ),
  );
}

export function getApiCompetitionsLeaderboardPaginationFromJSON(
  jsonString: string,
): SafeParseResult<
  GetApiCompetitionsLeaderboardPagination,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiCompetitionsLeaderboardPagination$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetApiCompetitionsLeaderboardPagination' from JSON`,
  );
}

/** @internal */
export const GetApiCompetitionsLeaderboardResponse$inboundSchema: z.ZodType<
  GetApiCompetitionsLeaderboardResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  competition: z
    .lazy(() => GetApiCompetitionsLeaderboardCompetition$inboundSchema)
    .optional(),
  leaderboard: z
    .array(z.lazy(() => GetApiCompetitionsLeaderboardLeaderboard$inboundSchema))
    .optional(),
  inactiveAgents: z.array(z.lazy(() => InactiveAgent$inboundSchema)).optional(),
  hasInactiveAgents: z.boolean().optional(),
  pagination: z
    .lazy(() => GetApiCompetitionsLeaderboardPagination$inboundSchema)
    .optional(),
});

/** @internal */
export type GetApiCompetitionsLeaderboardResponse$Outbound = {
  success?: boolean | undefined;
  competition?: GetApiCompetitionsLeaderboardCompetition$Outbound | undefined;
  leaderboard?:
    | Array<GetApiCompetitionsLeaderboardLeaderboard$Outbound>
    | undefined;
  inactiveAgents?: Array<InactiveAgent$Outbound> | undefined;
  hasInactiveAgents?: boolean | undefined;
  pagination?: GetApiCompetitionsLeaderboardPagination$Outbound | undefined;
};

/** @internal */
export const GetApiCompetitionsLeaderboardResponse$outboundSchema: z.ZodType<
  GetApiCompetitionsLeaderboardResponse$Outbound,
  z.ZodTypeDef,
  GetApiCompetitionsLeaderboardResponse
> = z.object({
  success: z.boolean().optional(),
  competition: z
    .lazy(() => GetApiCompetitionsLeaderboardCompetition$outboundSchema)
    .optional(),
  leaderboard: z
    .array(
      z.lazy(() => GetApiCompetitionsLeaderboardLeaderboard$outboundSchema),
    )
    .optional(),
  inactiveAgents: z
    .array(z.lazy(() => InactiveAgent$outboundSchema))
    .optional(),
  hasInactiveAgents: z.boolean().optional(),
  pagination: z
    .lazy(() => GetApiCompetitionsLeaderboardPagination$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiCompetitionsLeaderboardResponse$ {
  /** @deprecated use `GetApiCompetitionsLeaderboardResponse$inboundSchema` instead. */
  export const inboundSchema =
    GetApiCompetitionsLeaderboardResponse$inboundSchema;
  /** @deprecated use `GetApiCompetitionsLeaderboardResponse$outboundSchema` instead. */
  export const outboundSchema =
    GetApiCompetitionsLeaderboardResponse$outboundSchema;
  /** @deprecated use `GetApiCompetitionsLeaderboardResponse$Outbound` instead. */
  export type Outbound = GetApiCompetitionsLeaderboardResponse$Outbound;
}

export function getApiCompetitionsLeaderboardResponseToJSON(
  getApiCompetitionsLeaderboardResponse: GetApiCompetitionsLeaderboardResponse,
): string {
  return JSON.stringify(
    GetApiCompetitionsLeaderboardResponse$outboundSchema.parse(
      getApiCompetitionsLeaderboardResponse,
    ),
  );
}

export function getApiCompetitionsLeaderboardResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiCompetitionsLeaderboardResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiCompetitionsLeaderboardResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiCompetitionsLeaderboardResponse' from JSON`,
  );
}
