/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiAdminAgentsAgentIdKeyRequest = {
  /**
   * ID of the agent
   */
  agentId: string;
};

export type GetApiAdminAgentsAgentIdKeyAgent = {
  /**
   * Agent ID
   */
  id?: string | undefined;
  /**
   * Agent name
   */
  name?: string | undefined;
  /**
   * The agent's API key
   */
  apiKey?: string | undefined;
};

/**
 * API key retrieved successfully
 */
export type GetApiAdminAgentsAgentIdKeyResponse = {
  /**
   * Operation success status
   */
  success?: boolean | undefined;
  agent?: GetApiAdminAgentsAgentIdKeyAgent | undefined;
};

/** @internal */
export const GetApiAdminAgentsAgentIdKeyRequest$inboundSchema: z.ZodType<
  GetApiAdminAgentsAgentIdKeyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  agentId: z.string(),
});

/** @internal */
export type GetApiAdminAgentsAgentIdKeyRequest$Outbound = {
  agentId: string;
};

/** @internal */
export const GetApiAdminAgentsAgentIdKeyRequest$outboundSchema: z.ZodType<
  GetApiAdminAgentsAgentIdKeyRequest$Outbound,
  z.ZodTypeDef,
  GetApiAdminAgentsAgentIdKeyRequest
> = z.object({
  agentId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiAdminAgentsAgentIdKeyRequest$ {
  /** @deprecated use `GetApiAdminAgentsAgentIdKeyRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiAdminAgentsAgentIdKeyRequest$inboundSchema;
  /** @deprecated use `GetApiAdminAgentsAgentIdKeyRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetApiAdminAgentsAgentIdKeyRequest$outboundSchema;
  /** @deprecated use `GetApiAdminAgentsAgentIdKeyRequest$Outbound` instead. */
  export type Outbound = GetApiAdminAgentsAgentIdKeyRequest$Outbound;
}

export function getApiAdminAgentsAgentIdKeyRequestToJSON(
  getApiAdminAgentsAgentIdKeyRequest: GetApiAdminAgentsAgentIdKeyRequest,
): string {
  return JSON.stringify(
    GetApiAdminAgentsAgentIdKeyRequest$outboundSchema.parse(
      getApiAdminAgentsAgentIdKeyRequest,
    ),
  );
}

export function getApiAdminAgentsAgentIdKeyRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiAdminAgentsAgentIdKeyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiAdminAgentsAgentIdKeyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiAdminAgentsAgentIdKeyRequest' from JSON`,
  );
}

/** @internal */
export const GetApiAdminAgentsAgentIdKeyAgent$inboundSchema: z.ZodType<
  GetApiAdminAgentsAgentIdKeyAgent,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  apiKey: z.string().optional(),
});

/** @internal */
export type GetApiAdminAgentsAgentIdKeyAgent$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
  apiKey?: string | undefined;
};

/** @internal */
export const GetApiAdminAgentsAgentIdKeyAgent$outboundSchema: z.ZodType<
  GetApiAdminAgentsAgentIdKeyAgent$Outbound,
  z.ZodTypeDef,
  GetApiAdminAgentsAgentIdKeyAgent
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  apiKey: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiAdminAgentsAgentIdKeyAgent$ {
  /** @deprecated use `GetApiAdminAgentsAgentIdKeyAgent$inboundSchema` instead. */
  export const inboundSchema = GetApiAdminAgentsAgentIdKeyAgent$inboundSchema;
  /** @deprecated use `GetApiAdminAgentsAgentIdKeyAgent$outboundSchema` instead. */
  export const outboundSchema = GetApiAdminAgentsAgentIdKeyAgent$outboundSchema;
  /** @deprecated use `GetApiAdminAgentsAgentIdKeyAgent$Outbound` instead. */
  export type Outbound = GetApiAdminAgentsAgentIdKeyAgent$Outbound;
}

export function getApiAdminAgentsAgentIdKeyAgentToJSON(
  getApiAdminAgentsAgentIdKeyAgent: GetApiAdminAgentsAgentIdKeyAgent,
): string {
  return JSON.stringify(
    GetApiAdminAgentsAgentIdKeyAgent$outboundSchema.parse(
      getApiAdminAgentsAgentIdKeyAgent,
    ),
  );
}

export function getApiAdminAgentsAgentIdKeyAgentFromJSON(
  jsonString: string,
): SafeParseResult<GetApiAdminAgentsAgentIdKeyAgent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiAdminAgentsAgentIdKeyAgent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiAdminAgentsAgentIdKeyAgent' from JSON`,
  );
}

/** @internal */
export const GetApiAdminAgentsAgentIdKeyResponse$inboundSchema: z.ZodType<
  GetApiAdminAgentsAgentIdKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  agent: z.lazy(() => GetApiAdminAgentsAgentIdKeyAgent$inboundSchema)
    .optional(),
});

/** @internal */
export type GetApiAdminAgentsAgentIdKeyResponse$Outbound = {
  success?: boolean | undefined;
  agent?: GetApiAdminAgentsAgentIdKeyAgent$Outbound | undefined;
};

/** @internal */
export const GetApiAdminAgentsAgentIdKeyResponse$outboundSchema: z.ZodType<
  GetApiAdminAgentsAgentIdKeyResponse$Outbound,
  z.ZodTypeDef,
  GetApiAdminAgentsAgentIdKeyResponse
> = z.object({
  success: z.boolean().optional(),
  agent: z.lazy(() => GetApiAdminAgentsAgentIdKeyAgent$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiAdminAgentsAgentIdKeyResponse$ {
  /** @deprecated use `GetApiAdminAgentsAgentIdKeyResponse$inboundSchema` instead. */
  export const inboundSchema =
    GetApiAdminAgentsAgentIdKeyResponse$inboundSchema;
  /** @deprecated use `GetApiAdminAgentsAgentIdKeyResponse$outboundSchema` instead. */
  export const outboundSchema =
    GetApiAdminAgentsAgentIdKeyResponse$outboundSchema;
  /** @deprecated use `GetApiAdminAgentsAgentIdKeyResponse$Outbound` instead. */
  export type Outbound = GetApiAdminAgentsAgentIdKeyResponse$Outbound;
}

export function getApiAdminAgentsAgentIdKeyResponseToJSON(
  getApiAdminAgentsAgentIdKeyResponse: GetApiAdminAgentsAgentIdKeyResponse,
): string {
  return JSON.stringify(
    GetApiAdminAgentsAgentIdKeyResponse$outboundSchema.parse(
      getApiAdminAgentsAgentIdKeyResponse,
    ),
  );
}

export function getApiAdminAgentsAgentIdKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiAdminAgentsAgentIdKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiAdminAgentsAgentIdKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiAdminAgentsAgentIdKeyResponse' from JSON`,
  );
}
