/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * API key reset successfully
 */
export type PostApiAccountResetApiKeyResponse = {
  /**
   * Operation success status
   */
  success?: boolean | undefined;
  /**
   * New API key to use for future requests
   */
  apiKey?: string | undefined;
};

/** @internal */
export const PostApiAccountResetApiKeyResponse$inboundSchema: z.ZodType<
  PostApiAccountResetApiKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  apiKey: z.string().optional(),
});

/** @internal */
export type PostApiAccountResetApiKeyResponse$Outbound = {
  success?: boolean | undefined;
  apiKey?: string | undefined;
};

/** @internal */
export const PostApiAccountResetApiKeyResponse$outboundSchema: z.ZodType<
  PostApiAccountResetApiKeyResponse$Outbound,
  z.ZodTypeDef,
  PostApiAccountResetApiKeyResponse
> = z.object({
  success: z.boolean().optional(),
  apiKey: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiAccountResetApiKeyResponse$ {
  /** @deprecated use `PostApiAccountResetApiKeyResponse$inboundSchema` instead. */
  export const inboundSchema = PostApiAccountResetApiKeyResponse$inboundSchema;
  /** @deprecated use `PostApiAccountResetApiKeyResponse$outboundSchema` instead. */
  export const outboundSchema =
    PostApiAccountResetApiKeyResponse$outboundSchema;
  /** @deprecated use `PostApiAccountResetApiKeyResponse$Outbound` instead. */
  export type Outbound = PostApiAccountResetApiKeyResponse$Outbound;
}

export function postApiAccountResetApiKeyResponseToJSON(
  postApiAccountResetApiKeyResponse: PostApiAccountResetApiKeyResponse,
): string {
  return JSON.stringify(
    PostApiAccountResetApiKeyResponse$outboundSchema.parse(
      postApiAccountResetApiKeyResponse,
    ),
  );
}

export function postApiAccountResetApiKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiAccountResetApiKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiAccountResetApiKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiAccountResetApiKeyResponse' from JSON`,
  );
}
