/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";

import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Logout successful
 */
export type PostApiAuthLogoutResponse = {
  message: string;
};

/** @internal */
export const PostApiAuthLogoutResponse$inboundSchema: z.ZodType<
  PostApiAuthLogoutResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

/** @internal */
export type PostApiAuthLogoutResponse$Outbound = {
  message: string;
};

/** @internal */
export const PostApiAuthLogoutResponse$outboundSchema: z.ZodType<
  PostApiAuthLogoutResponse$Outbound,
  z.ZodTypeDef,
  PostApiAuthLogoutResponse
> = z.object({
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiAuthLogoutResponse$ {
  /** @deprecated use `PostApiAuthLogoutResponse$inboundSchema` instead. */
  export const inboundSchema = PostApiAuthLogoutResponse$inboundSchema;
  /** @deprecated use `PostApiAuthLogoutResponse$outboundSchema` instead. */
  export const outboundSchema = PostApiAuthLogoutResponse$outboundSchema;
  /** @deprecated use `PostApiAuthLogoutResponse$Outbound` instead. */
  export type Outbound = PostApiAuthLogoutResponse$Outbound;
}

export function postApiAuthLogoutResponseToJSON(
  postApiAuthLogoutResponse: PostApiAuthLogoutResponse,
): string {
  return JSON.stringify(
    PostApiAuthLogoutResponse$outboundSchema.parse(postApiAuthLogoutResponse),
  );
}

export function postApiAuthLogoutResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiAuthLogoutResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiAuthLogoutResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiAuthLogoutResponse' from JSON`,
  );
}
