/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";

import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiAdminTeamsTeamIdReactivateRequest = {
  /**
   * ID of the team to reactivate
   */
  teamId: string;
};

export type PostApiAdminTeamsTeamIdReactivateTeam = {
  /**
   * Team ID
   */
  id?: string | undefined;
  /**
   * Team name
   */
  name?: string | undefined;
  /**
   * Active status (will be true)
   */
  active?: boolean | undefined;
};

/**
 * Team reactivated successfully
 */
export type PostApiAdminTeamsTeamIdReactivateResponse = {
  /**
   * Operation success status
   */
  success?: boolean | undefined;
  team?: PostApiAdminTeamsTeamIdReactivateTeam | undefined;
};

/** @internal */
export const PostApiAdminTeamsTeamIdReactivateRequest$inboundSchema: z.ZodType<
  PostApiAdminTeamsTeamIdReactivateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  teamId: z.string(),
});

/** @internal */
export type PostApiAdminTeamsTeamIdReactivateRequest$Outbound = {
  teamId: string;
};

/** @internal */
export const PostApiAdminTeamsTeamIdReactivateRequest$outboundSchema: z.ZodType<
  PostApiAdminTeamsTeamIdReactivateRequest$Outbound,
  z.ZodTypeDef,
  PostApiAdminTeamsTeamIdReactivateRequest
> = z.object({
  teamId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiAdminTeamsTeamIdReactivateRequest$ {
  /** @deprecated use `PostApiAdminTeamsTeamIdReactivateRequest$inboundSchema` instead. */
  export const inboundSchema =
    PostApiAdminTeamsTeamIdReactivateRequest$inboundSchema;
  /** @deprecated use `PostApiAdminTeamsTeamIdReactivateRequest$outboundSchema` instead. */
  export const outboundSchema =
    PostApiAdminTeamsTeamIdReactivateRequest$outboundSchema;
  /** @deprecated use `PostApiAdminTeamsTeamIdReactivateRequest$Outbound` instead. */
  export type Outbound = PostApiAdminTeamsTeamIdReactivateRequest$Outbound;
}

export function postApiAdminTeamsTeamIdReactivateRequestToJSON(
  postApiAdminTeamsTeamIdReactivateRequest: PostApiAdminTeamsTeamIdReactivateRequest,
): string {
  return JSON.stringify(
    PostApiAdminTeamsTeamIdReactivateRequest$outboundSchema.parse(
      postApiAdminTeamsTeamIdReactivateRequest,
    ),
  );
}

export function postApiAdminTeamsTeamIdReactivateRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiAdminTeamsTeamIdReactivateRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiAdminTeamsTeamIdReactivateRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiAdminTeamsTeamIdReactivateRequest' from JSON`,
  );
}

/** @internal */
export const PostApiAdminTeamsTeamIdReactivateTeam$inboundSchema: z.ZodType<
  PostApiAdminTeamsTeamIdReactivateTeam,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  active: z.boolean().optional(),
});

/** @internal */
export type PostApiAdminTeamsTeamIdReactivateTeam$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
  active?: boolean | undefined;
};

/** @internal */
export const PostApiAdminTeamsTeamIdReactivateTeam$outboundSchema: z.ZodType<
  PostApiAdminTeamsTeamIdReactivateTeam$Outbound,
  z.ZodTypeDef,
  PostApiAdminTeamsTeamIdReactivateTeam
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  active: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiAdminTeamsTeamIdReactivateTeam$ {
  /** @deprecated use `PostApiAdminTeamsTeamIdReactivateTeam$inboundSchema` instead. */
  export const inboundSchema =
    PostApiAdminTeamsTeamIdReactivateTeam$inboundSchema;
  /** @deprecated use `PostApiAdminTeamsTeamIdReactivateTeam$outboundSchema` instead. */
  export const outboundSchema =
    PostApiAdminTeamsTeamIdReactivateTeam$outboundSchema;
  /** @deprecated use `PostApiAdminTeamsTeamIdReactivateTeam$Outbound` instead. */
  export type Outbound = PostApiAdminTeamsTeamIdReactivateTeam$Outbound;
}

export function postApiAdminTeamsTeamIdReactivateTeamToJSON(
  postApiAdminTeamsTeamIdReactivateTeam: PostApiAdminTeamsTeamIdReactivateTeam,
): string {
  return JSON.stringify(
    PostApiAdminTeamsTeamIdReactivateTeam$outboundSchema.parse(
      postApiAdminTeamsTeamIdReactivateTeam,
    ),
  );
}

export function postApiAdminTeamsTeamIdReactivateTeamFromJSON(
  jsonString: string,
): SafeParseResult<PostApiAdminTeamsTeamIdReactivateTeam, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiAdminTeamsTeamIdReactivateTeam$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiAdminTeamsTeamIdReactivateTeam' from JSON`,
  );
}

/** @internal */
export const PostApiAdminTeamsTeamIdReactivateResponse$inboundSchema: z.ZodType<
  PostApiAdminTeamsTeamIdReactivateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  team: z
    .lazy(() => PostApiAdminTeamsTeamIdReactivateTeam$inboundSchema)
    .optional(),
});

/** @internal */
export type PostApiAdminTeamsTeamIdReactivateResponse$Outbound = {
  success?: boolean | undefined;
  team?: PostApiAdminTeamsTeamIdReactivateTeam$Outbound | undefined;
};

/** @internal */
export const PostApiAdminTeamsTeamIdReactivateResponse$outboundSchema: z.ZodType<
  PostApiAdminTeamsTeamIdReactivateResponse$Outbound,
  z.ZodTypeDef,
  PostApiAdminTeamsTeamIdReactivateResponse
> = z.object({
  success: z.boolean().optional(),
  team: z
    .lazy(() => PostApiAdminTeamsTeamIdReactivateTeam$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiAdminTeamsTeamIdReactivateResponse$ {
  /** @deprecated use `PostApiAdminTeamsTeamIdReactivateResponse$inboundSchema` instead. */
  export const inboundSchema =
    PostApiAdminTeamsTeamIdReactivateResponse$inboundSchema;
  /** @deprecated use `PostApiAdminTeamsTeamIdReactivateResponse$outboundSchema` instead. */
  export const outboundSchema =
    PostApiAdminTeamsTeamIdReactivateResponse$outboundSchema;
  /** @deprecated use `PostApiAdminTeamsTeamIdReactivateResponse$Outbound` instead. */
  export type Outbound = PostApiAdminTeamsTeamIdReactivateResponse$Outbound;
}

export function postApiAdminTeamsTeamIdReactivateResponseToJSON(
  postApiAdminTeamsTeamIdReactivateResponse: PostApiAdminTeamsTeamIdReactivateResponse,
): string {
  return JSON.stringify(
    PostApiAdminTeamsTeamIdReactivateResponse$outboundSchema.parse(
      postApiAdminTeamsTeamIdReactivateResponse,
    ),
  );
}

export function postApiAdminTeamsTeamIdReactivateResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiAdminTeamsTeamIdReactivateResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiAdminTeamsTeamIdReactivateResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiAdminTeamsTeamIdReactivateResponse' from JSON`,
  );
}
