/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * API key reset successfully
 */
export type PostApiAgentResetApiKeyResponse = {
  success?: boolean | undefined;
  /**
   * The new API key (store this securely)
   */
  apiKey?: string | undefined;
};

/** @internal */
export const PostApiAgentResetApiKeyResponse$inboundSchema: z.ZodType<
  PostApiAgentResetApiKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  apiKey: z.string().optional(),
});

/** @internal */
export type PostApiAgentResetApiKeyResponse$Outbound = {
  success?: boolean | undefined;
  apiKey?: string | undefined;
};

/** @internal */
export const PostApiAgentResetApiKeyResponse$outboundSchema: z.ZodType<
  PostApiAgentResetApiKeyResponse$Outbound,
  z.ZodTypeDef,
  PostApiAgentResetApiKeyResponse
> = z.object({
  success: z.boolean().optional(),
  apiKey: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiAgentResetApiKeyResponse$ {
  /** @deprecated use `PostApiAgentResetApiKeyResponse$inboundSchema` instead. */
  export const inboundSchema = PostApiAgentResetApiKeyResponse$inboundSchema;
  /** @deprecated use `PostApiAgentResetApiKeyResponse$outboundSchema` instead. */
  export const outboundSchema = PostApiAgentResetApiKeyResponse$outboundSchema;
  /** @deprecated use `PostApiAgentResetApiKeyResponse$Outbound` instead. */
  export type Outbound = PostApiAgentResetApiKeyResponse$Outbound;
}

export function postApiAgentResetApiKeyResponseToJSON(
  postApiAgentResetApiKeyResponse: PostApiAgentResetApiKeyResponse,
): string {
  return JSON.stringify(
    PostApiAgentResetApiKeyResponse$outboundSchema.parse(
      postApiAgentResetApiKeyResponse,
    ),
  );
}

export function postApiAgentResetApiKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiAgentResetApiKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiAgentResetApiKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiAgentResetApiKeyResponse' from JSON`,
  );
}
