/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";

import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Type of cross-chain trading to allow in this competition (used when creating a new competition)
 */
export const PostApiAdminCompetitionStartTradingType = {
  DisallowAll: "disallowAll",
  DisallowXParent: "disallowXParent",
  Allow: "allow",
} as const;
/**
 * Type of cross-chain trading to allow in this competition (used when creating a new competition)
 */
export type PostApiAdminCompetitionStartTradingType = ClosedEnum<
  typeof PostApiAdminCompetitionStartTradingType
>;

export type PostApiAdminCompetitionStartRequest = {
  /**
   * ID of an existing competition to start. If not provided, a new competition will be created.
   */
  competitionId?: string | undefined;
  /**
   * Competition name (required when creating a new competition)
   */
  name?: string | undefined;
  /**
   * Competition description (used when creating a new competition)
   */
  description?: string | undefined;
  /**
   * External URL for competition details (used when creating a new competition)
   */
  externalLink?: string | undefined;
  /**
   * URL to competition image (used when creating a new competition)
   */
  imageUrl?: string | undefined;
  /**
   * Array of team IDs to include in the competition
   */
  teamIds: Array<string>;
  /**
   * Type of cross-chain trading to allow in this competition (used when creating a new competition)
   */
  tradingType?: PostApiAdminCompetitionStartTradingType | undefined;
};

/**
 * Competition status
 */
export const PostApiAdminCompetitionStartStatus = {
  Pending: "PENDING",
  Active: "ACTIVE",
  Completed: "COMPLETED",
} as const;
/**
 * Competition status
 */
export type PostApiAdminCompetitionStartStatus = ClosedEnum<
  typeof PostApiAdminCompetitionStartStatus
>;

/**
 * Type of cross-chain trading allowed in this competition
 */
export const PostApiAdminCompetitionStartCrossChainTradingType = {
  DisallowAll: "disallowAll",
  DisallowXParent: "disallowXParent",
  Allow: "allow",
} as const;
/**
 * Type of cross-chain trading allowed in this competition
 */
export type PostApiAdminCompetitionStartCrossChainTradingType = ClosedEnum<
  typeof PostApiAdminCompetitionStartCrossChainTradingType
>;

export type PostApiAdminCompetitionStartCompetition = {
  /**
   * Competition ID
   */
  id?: string | undefined;
  /**
   * Competition name
   */
  name?: string | undefined;
  /**
   * Competition description
   */
  description?: string | undefined;
  /**
   * Competition start date
   */
  startDate?: Date | undefined;
  /**
   * Competition end date (null if not ended)
   */
  endDate?: Date | null | undefined;
  /**
   * External URL for competition details
   */
  externalLink?: string | null | undefined;
  /**
   * URL to competition image
   */
  imageUrl?: string | null | undefined;
  /**
   * Competition status
   */
  status?: PostApiAdminCompetitionStartStatus | undefined;
  /**
   * Type of cross-chain trading allowed in this competition
   */
  crossChainTradingType?:
    | PostApiAdminCompetitionStartCrossChainTradingType
    | undefined;
  /**
   * Team IDs participating in the competition
   */
  teamIds?: Array<string> | undefined;
};

/**
 * Competition started successfully
 */
export type PostApiAdminCompetitionStartResponse = {
  /**
   * Operation success status
   */
  success?: boolean | undefined;
  competition?: PostApiAdminCompetitionStartCompetition | undefined;
};

/** @internal */
export const PostApiAdminCompetitionStartTradingType$inboundSchema: z.ZodNativeEnum<
  typeof PostApiAdminCompetitionStartTradingType
> = z.nativeEnum(PostApiAdminCompetitionStartTradingType);

/** @internal */
export const PostApiAdminCompetitionStartTradingType$outboundSchema: z.ZodNativeEnum<
  typeof PostApiAdminCompetitionStartTradingType
> = PostApiAdminCompetitionStartTradingType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiAdminCompetitionStartTradingType$ {
  /** @deprecated use `PostApiAdminCompetitionStartTradingType$inboundSchema` instead. */
  export const inboundSchema =
    PostApiAdminCompetitionStartTradingType$inboundSchema;
  /** @deprecated use `PostApiAdminCompetitionStartTradingType$outboundSchema` instead. */
  export const outboundSchema =
    PostApiAdminCompetitionStartTradingType$outboundSchema;
}

/** @internal */
export const PostApiAdminCompetitionStartRequest$inboundSchema: z.ZodType<
  PostApiAdminCompetitionStartRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  competitionId: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  externalLink: z.string().optional(),
  imageUrl: z.string().optional(),
  teamIds: z.array(z.string()),
  tradingType:
    PostApiAdminCompetitionStartTradingType$inboundSchema.default(
      "disallowAll",
    ),
});

/** @internal */
export type PostApiAdminCompetitionStartRequest$Outbound = {
  competitionId?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  externalLink?: string | undefined;
  imageUrl?: string | undefined;
  teamIds: Array<string>;
  tradingType: string;
};

/** @internal */
export const PostApiAdminCompetitionStartRequest$outboundSchema: z.ZodType<
  PostApiAdminCompetitionStartRequest$Outbound,
  z.ZodTypeDef,
  PostApiAdminCompetitionStartRequest
> = z.object({
  competitionId: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  externalLink: z.string().optional(),
  imageUrl: z.string().optional(),
  teamIds: z.array(z.string()),
  tradingType:
    PostApiAdminCompetitionStartTradingType$outboundSchema.default(
      "disallowAll",
    ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiAdminCompetitionStartRequest$ {
  /** @deprecated use `PostApiAdminCompetitionStartRequest$inboundSchema` instead. */
  export const inboundSchema =
    PostApiAdminCompetitionStartRequest$inboundSchema;
  /** @deprecated use `PostApiAdminCompetitionStartRequest$outboundSchema` instead. */
  export const outboundSchema =
    PostApiAdminCompetitionStartRequest$outboundSchema;
  /** @deprecated use `PostApiAdminCompetitionStartRequest$Outbound` instead. */
  export type Outbound = PostApiAdminCompetitionStartRequest$Outbound;
}

export function postApiAdminCompetitionStartRequestToJSON(
  postApiAdminCompetitionStartRequest: PostApiAdminCompetitionStartRequest,
): string {
  return JSON.stringify(
    PostApiAdminCompetitionStartRequest$outboundSchema.parse(
      postApiAdminCompetitionStartRequest,
    ),
  );
}

export function postApiAdminCompetitionStartRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostApiAdminCompetitionStartRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiAdminCompetitionStartRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiAdminCompetitionStartRequest' from JSON`,
  );
}

/** @internal */
export const PostApiAdminCompetitionStartStatus$inboundSchema: z.ZodNativeEnum<
  typeof PostApiAdminCompetitionStartStatus
> = z.nativeEnum(PostApiAdminCompetitionStartStatus);

/** @internal */
export const PostApiAdminCompetitionStartStatus$outboundSchema: z.ZodNativeEnum<
  typeof PostApiAdminCompetitionStartStatus
> = PostApiAdminCompetitionStartStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiAdminCompetitionStartStatus$ {
  /** @deprecated use `PostApiAdminCompetitionStartStatus$inboundSchema` instead. */
  export const inboundSchema = PostApiAdminCompetitionStartStatus$inboundSchema;
  /** @deprecated use `PostApiAdminCompetitionStartStatus$outboundSchema` instead. */
  export const outboundSchema =
    PostApiAdminCompetitionStartStatus$outboundSchema;
}

/** @internal */
export const PostApiAdminCompetitionStartCrossChainTradingType$inboundSchema: z.ZodNativeEnum<
  typeof PostApiAdminCompetitionStartCrossChainTradingType
> = z.nativeEnum(PostApiAdminCompetitionStartCrossChainTradingType);

/** @internal */
export const PostApiAdminCompetitionStartCrossChainTradingType$outboundSchema: z.ZodNativeEnum<
  typeof PostApiAdminCompetitionStartCrossChainTradingType
> = PostApiAdminCompetitionStartCrossChainTradingType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiAdminCompetitionStartCrossChainTradingType$ {
  /** @deprecated use `PostApiAdminCompetitionStartCrossChainTradingType$inboundSchema` instead. */
  export const inboundSchema =
    PostApiAdminCompetitionStartCrossChainTradingType$inboundSchema;
  /** @deprecated use `PostApiAdminCompetitionStartCrossChainTradingType$outboundSchema` instead. */
  export const outboundSchema =
    PostApiAdminCompetitionStartCrossChainTradingType$outboundSchema;
}

/** @internal */
export const PostApiAdminCompetitionStartCompetition$inboundSchema: z.ZodType<
  PostApiAdminCompetitionStartCompetition,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  startDate: z
    .string()
    .datetime({ offset: true })
    .transform((v) => new Date(v))
    .optional(),
  endDate: z
    .nullable(
      z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    )
    .optional(),
  externalLink: z.nullable(z.string()).optional(),
  imageUrl: z.nullable(z.string()).optional(),
  status: PostApiAdminCompetitionStartStatus$inboundSchema.optional(),
  crossChainTradingType:
    PostApiAdminCompetitionStartCrossChainTradingType$inboundSchema.optional(),
  teamIds: z.array(z.string()).optional(),
});

/** @internal */
export type PostApiAdminCompetitionStartCompetition$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | null | undefined;
  externalLink?: string | null | undefined;
  imageUrl?: string | null | undefined;
  status?: string | undefined;
  crossChainTradingType?: string | undefined;
  teamIds?: Array<string> | undefined;
};

/** @internal */
export const PostApiAdminCompetitionStartCompetition$outboundSchema: z.ZodType<
  PostApiAdminCompetitionStartCompetition$Outbound,
  z.ZodTypeDef,
  PostApiAdminCompetitionStartCompetition
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  startDate: z
    .date()
    .transform((v) => v.toISOString())
    .optional(),
  endDate: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
  externalLink: z.nullable(z.string()).optional(),
  imageUrl: z.nullable(z.string()).optional(),
  status: PostApiAdminCompetitionStartStatus$outboundSchema.optional(),
  crossChainTradingType:
    PostApiAdminCompetitionStartCrossChainTradingType$outboundSchema.optional(),
  teamIds: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiAdminCompetitionStartCompetition$ {
  /** @deprecated use `PostApiAdminCompetitionStartCompetition$inboundSchema` instead. */
  export const inboundSchema =
    PostApiAdminCompetitionStartCompetition$inboundSchema;
  /** @deprecated use `PostApiAdminCompetitionStartCompetition$outboundSchema` instead. */
  export const outboundSchema =
    PostApiAdminCompetitionStartCompetition$outboundSchema;
  /** @deprecated use `PostApiAdminCompetitionStartCompetition$Outbound` instead. */
  export type Outbound = PostApiAdminCompetitionStartCompetition$Outbound;
}

export function postApiAdminCompetitionStartCompetitionToJSON(
  postApiAdminCompetitionStartCompetition: PostApiAdminCompetitionStartCompetition,
): string {
  return JSON.stringify(
    PostApiAdminCompetitionStartCompetition$outboundSchema.parse(
      postApiAdminCompetitionStartCompetition,
    ),
  );
}

export function postApiAdminCompetitionStartCompetitionFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiAdminCompetitionStartCompetition,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiAdminCompetitionStartCompetition$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiAdminCompetitionStartCompetition' from JSON`,
  );
}

/** @internal */
export const PostApiAdminCompetitionStartResponse$inboundSchema: z.ZodType<
  PostApiAdminCompetitionStartResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  competition: z
    .lazy(() => PostApiAdminCompetitionStartCompetition$inboundSchema)
    .optional(),
});

/** @internal */
export type PostApiAdminCompetitionStartResponse$Outbound = {
  success?: boolean | undefined;
  competition?: PostApiAdminCompetitionStartCompetition$Outbound | undefined;
};

/** @internal */
export const PostApiAdminCompetitionStartResponse$outboundSchema: z.ZodType<
  PostApiAdminCompetitionStartResponse$Outbound,
  z.ZodTypeDef,
  PostApiAdminCompetitionStartResponse
> = z.object({
  success: z.boolean().optional(),
  competition: z
    .lazy(() => PostApiAdminCompetitionStartCompetition$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiAdminCompetitionStartResponse$ {
  /** @deprecated use `PostApiAdminCompetitionStartResponse$inboundSchema` instead. */
  export const inboundSchema =
    PostApiAdminCompetitionStartResponse$inboundSchema;
  /** @deprecated use `PostApiAdminCompetitionStartResponse$outboundSchema` instead. */
  export const outboundSchema =
    PostApiAdminCompetitionStartResponse$outboundSchema;
  /** @deprecated use `PostApiAdminCompetitionStartResponse$Outbound` instead. */
  export type Outbound = PostApiAdminCompetitionStartResponse$Outbound;
}

export function postApiAdminCompetitionStartResponseToJSON(
  postApiAdminCompetitionStartResponse: PostApiAdminCompetitionStartResponse,
): string {
  return JSON.stringify(
    PostApiAdminCompetitionStartResponse$outboundSchema.parse(
      postApiAdminCompetitionStartResponse,
    ),
  );
}

export function postApiAdminCompetitionStartResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiAdminCompetitionStartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiAdminCompetitionStartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiAdminCompetitionStartResponse' from JSON`,
  );
}
