/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import dotenv from "dotenv";

/**
 * Example usage of the @recallnet/api-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx adminPostApiAdminSetup.ts
 */

import { ApiSDK } from "@recallnet/api-sdk";

dotenv.config();

const apiSDK = new ApiSDK({
  bearerAuth: process.env["APISDK_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await apiSDK.postApiAdminSetup({
    username: "admin",
    password: "password123",
    email: "admin@example.com",
  });

  console.log(result);
}

main().catch(console.error);
