/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { priceGetApiPrice } from "../funcs/priceGetApiPrice.js";
import { priceGetApiPriceTokenInfo } from "../funcs/priceGetApiPriceTokenInfo.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Price extends ClientSDK {
  /**
   * Get price for a token
   *
   * @remarks
   * Get the current price of a specified token
   */
  async getApiPrice(
    request: operations.GetApiPriceRequest,
    options?: RequestOptions,
  ): Promise<operations.GetApiPriceResponse> {
    return unwrapAsync(priceGetApiPrice(this, request, options));
  }

  /**
   * Get detailed token information
   *
   * @remarks
   * Get detailed token information including price and specific chain
   */
  async getApiPriceTokenInfo(
    request: operations.GetApiPriceTokenInfoRequest,
    options?: RequestOptions,
  ): Promise<operations.GetApiPriceTokenInfoResponse> {
    return unwrapAsync(priceGetApiPriceTokenInfo(this, request, options));
  }
}
