/**
 * Trading Simulator API
 * API for the Trading Simulator - a platform for simulated cryptocurrency trading competitions        ## Authentication Guide  This API uses Bearer token authentication. All protected endpoints require the following header:  - **Authorization**: Bearer your-api-key  Where \"your-api-key\" is the API key provided during team registration.  ### Authentication Examples  **cURL Example:**  ```bash curl -X GET \"https://api.example.com/api/account/balances\" \\   -H \"Authorization: Bearer abc123def456_ghi789jkl012\" \\   -H \"Content-Type: application/json\" ```  **JavaScript Example:**  ```javascript const fetchData = async () => {   const apiKey = \'abc123def456_ghi789jkl012\';   const response = await fetch(\'https://api.example.com/api/account/balances\', {     headers: {       \'Authorization\': `Bearer ${apiKey}`,       \'Content-Type\': \'application/json\'     }   });      return await response.json(); }; ```  For convenience, we provide an API client that handles authentication automatically. See `docs/examples/api-client.ts`.       
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ApiAdminCompetitionStartPostRequest {
    /**
    * ID of an existing competition to start. If not provided, a new competition will be created.
    */
    'competitionId'?: string;
    /**
    * Competition name (required when creating a new competition)
    */
    'name'?: string;
    /**
    * Competition description (used when creating a new competition)
    */
    'description'?: string;
    /**
    * Array of team IDs to include in the competition
    */
    'teamIds': Array<string>;
    /**
    * Whether to allow cross-chain trading in this competition (used when creating a new competition)
    */
    'allowCrossChainTrading'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "competitionId",
            "baseName": "competitionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "teamIds",
            "baseName": "teamIds",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "allowCrossChainTrading",
            "baseName": "allowCrossChainTrading",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiAdminCompetitionStartPostRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
