/**
 * Trading Simulator API
 * API for the Trading Simulator - a platform for simulated cryptocurrency trading competitions        ## Authentication Guide  This API uses Bearer token authentication. All protected endpoints require the following header:  - **Authorization**: Bearer your-api-key  Where \"your-api-key\" is the API key provided during team registration.  ### Authentication Examples  **cURL Example:**  ```bash curl -X GET \"https://api.example.com/api/account/balances\" \\   -H \"Authorization: Bearer abc123def456_ghi789jkl012\" \\   -H \"Content-Type: application/json\" ```  **JavaScript Example:**  ```javascript const fetchData = async () => {   const apiKey = \'abc123def456_ghi789jkl012\';   const response = await fetch(\'https://api.example.com/api/account/balances\', {     headers: {       \'Authorization\': `Bearer ${apiKey}`,       \'Content-Type\': \'application/json\'     }   });      return await response.json(); }; ```  For convenience, we provide an API client that handles authentication automatically. See `docs/examples/api-client.ts`.       
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ApiPriceTokenInfoGet200Response {
    /**
    * Whether the token information was successfully retrieved
    */
    'success'?: boolean;
    /**
    * Current price of the token in USD
    */
    'price'?: number | null;
    /**
    * Token address
    */
    'token'?: string;
    /**
    * Blockchain type of the token
    */
    'chain'?: ApiPriceTokenInfoGet200ResponseChainEnum;
    /**
    * Specific chain for EVM tokens
    */
    'specificChain'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string",
            "format": ""
        },
        {
            "name": "chain",
            "baseName": "chain",
            "type": "ApiPriceTokenInfoGet200ResponseChainEnum",
            "format": ""
        },
        {
            "name": "specificChain",
            "baseName": "specificChain",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiPriceTokenInfoGet200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ApiPriceTokenInfoGet200ResponseChainEnum {
    Evm = 'EVM',
    Svm = 'SVM'
}

