/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";

import { APISDKError } from "./apisdkerror.js";

/**
 * User has already voted in this competition
 */
export type ConflictErrorData = {
  success?: boolean | undefined;
  error?: string | undefined;
};

/**
 * User has already voted in this competition
 */
export class ConflictError extends APISDKError {
  success?: boolean | undefined;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ConflictErrorData;

  constructor(
    err: ConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message =
      "message" in err && typeof err.message === "string"
        ? err.message
        : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "ConflictError";
  }
}

/**
 * Invalid request or voting not allowed
 */
export type PostApiUserVoteBadRequestErrorData = {
  success?: boolean | undefined;
  error?: string | undefined;
};

/**
 * Invalid request or voting not allowed
 */
export class PostApiUserVoteBadRequestError extends APISDKError {
  success?: boolean | undefined;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostApiUserVoteBadRequestErrorData;

  constructor(
    err: PostApiUserVoteBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message =
      "message" in err && typeof err.message === "string"
        ? err.message
        : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "PostApiUserVoteBadRequestError";
  }
}

/** @internal */
export const ConflictError$inboundSchema: z.ZodType<
  ConflictError,
  z.ZodTypeDef,
  unknown
> = z
  .object({
    success: z.boolean().optional(),
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
  .transform((v) => {
    return new ConflictError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ConflictError$Outbound = {
  success?: boolean | undefined;
  error?: string | undefined;
};

/** @internal */
export const ConflictError$outboundSchema: z.ZodType<
  ConflictError$Outbound,
  z.ZodTypeDef,
  ConflictError
> = z
  .instanceof(ConflictError)
  .transform((v) => v.data$)
  .pipe(
    z.object({
      success: z.boolean().optional(),
      error: z.string().optional(),
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConflictError$ {
  /** @deprecated use `ConflictError$inboundSchema` instead. */
  export const inboundSchema = ConflictError$inboundSchema;
  /** @deprecated use `ConflictError$outboundSchema` instead. */
  export const outboundSchema = ConflictError$outboundSchema;
  /** @deprecated use `ConflictError$Outbound` instead. */
  export type Outbound = ConflictError$Outbound;
}

/** @internal */
export const PostApiUserVoteBadRequestError$inboundSchema: z.ZodType<
  PostApiUserVoteBadRequestError,
  z.ZodTypeDef,
  unknown
> = z
  .object({
    success: z.boolean().optional(),
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
  .transform((v) => {
    return new PostApiUserVoteBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostApiUserVoteBadRequestError$Outbound = {
  success?: boolean | undefined;
  error?: string | undefined;
};

/** @internal */
export const PostApiUserVoteBadRequestError$outboundSchema: z.ZodType<
  PostApiUserVoteBadRequestError$Outbound,
  z.ZodTypeDef,
  PostApiUserVoteBadRequestError
> = z
  .instanceof(PostApiUserVoteBadRequestError)
  .transform((v) => v.data$)
  .pipe(
    z.object({
      success: z.boolean().optional(),
      error: z.string().optional(),
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiUserVoteBadRequestError$ {
  /** @deprecated use `PostApiUserVoteBadRequestError$inboundSchema` instead. */
  export const inboundSchema = PostApiUserVoteBadRequestError$inboundSchema;
  /** @deprecated use `PostApiUserVoteBadRequestError$outboundSchema` instead. */
  export const outboundSchema = PostApiUserVoteBadRequestError$outboundSchema;
  /** @deprecated use `PostApiUserVoteBadRequestError$Outbound` instead. */
  export type Outbound = PostApiUserVoteBadRequestError$Outbound;
}
