/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";

import { APISDKError } from "./apisdkerror.js";

/**
 * User does not have an email address
 */
export type PostApiUserVerifyEmailBadRequestErrorData = {
  success?: boolean | undefined;
  error?: string | undefined;
};

/**
 * User does not have an email address
 */
export class PostApiUserVerifyEmailBadRequestError extends APISDKError {
  success?: boolean | undefined;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostApiUserVerifyEmailBadRequestErrorData;

  constructor(
    err: PostApiUserVerifyEmailBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message =
      "message" in err && typeof err.message === "string"
        ? err.message
        : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "PostApiUserVerifyEmailBadRequestError";
  }
}

/** @internal */
export const PostApiUserVerifyEmailBadRequestError$inboundSchema: z.ZodType<
  PostApiUserVerifyEmailBadRequestError,
  z.ZodTypeDef,
  unknown
> = z
  .object({
    success: z.boolean().optional(),
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
  .transform((v) => {
    return new PostApiUserVerifyEmailBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostApiUserVerifyEmailBadRequestError$Outbound = {
  success?: boolean | undefined;
  error?: string | undefined;
};

/** @internal */
export const PostApiUserVerifyEmailBadRequestError$outboundSchema: z.ZodType<
  PostApiUserVerifyEmailBadRequestError$Outbound,
  z.ZodTypeDef,
  PostApiUserVerifyEmailBadRequestError
> = z
  .instanceof(PostApiUserVerifyEmailBadRequestError)
  .transform((v) => v.data$)
  .pipe(
    z.object({
      success: z.boolean().optional(),
      error: z.string().optional(),
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiUserVerifyEmailBadRequestError$ {
  /** @deprecated use `PostApiUserVerifyEmailBadRequestError$inboundSchema` instead. */
  export const inboundSchema =
    PostApiUserVerifyEmailBadRequestError$inboundSchema;
  /** @deprecated use `PostApiUserVerifyEmailBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    PostApiUserVerifyEmailBadRequestError$outboundSchema;
  /** @deprecated use `PostApiUserVerifyEmailBadRequestError$Outbound` instead. */
  export type Outbound = PostApiUserVerifyEmailBadRequestError$Outbound;
}
