/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountGetApiAccountTrades } from "../../funcs/accountGetApiAccountTrades.js";
import { ToolDefinition, formatResult } from "../tools.js";

export const tool$accountGetApiAccountTrades: ToolDefinition = {
  name: "account-get-api-account-trades",
  description: `Get trade history

Get trade history for the authenticated team`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await accountGetApiAccountTrades(client, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
