/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountGetApiAccountBalances } from "../../funcs/accountGetApiAccountBalances.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$accountGetApiAccountBalances: ToolDefinition = {
  name: "account-get-api-account-balances",
  description: `Get token balances

Get all token balances for the authenticated team`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await accountGetApiAccountBalances(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
