/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminPostApiAdminCompetitionStart } from "../../funcs/adminPostApiAdminCompetitionStart.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiAdminCompetitionStartRequest$inboundSchema,
};

export const tool$adminPostApiAdminCompetitionStart: ToolDefinition<
  typeof args
> = {
  name: "admin-post-api-admin-competition-start",
  description: `Start a competition

Start a new or existing competition with specified teams. If competitionId is provided, it will start an existing competition. Otherwise, it will create and start a new one.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await adminPostApiAdminCompetitionStart(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
