/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { adminPostApiAdminAgents } from "../../funcs/adminPostApiAdminAgents.js";
import * as operations from "../../models/operations/index.js";
import { ToolDefinition, formatResult } from "../tools.js";

const args = {
  request: operations.PostApiAdminAgentsRequest$inboundSchema,
};

export const tool$adminPostApiAdminAgents: ToolDefinition<typeof args> = {
  name: "admin-post-api-admin-agents",
  description: `Register a new agent

Admin-only endpoint to register a new agent. Admins create agent accounts and distribute the generated API keys to agents.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await adminPostApiAdminAgents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
