/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentPostApiAgentResetApiKey } from "../../funcs/agentPostApiAgentResetApiKey.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$agentPostApiAgentResetApiKey: ToolDefinition = {
  name: "agent-post-api-agent-reset-api-key",
  description: `Reset agent API key

Generate a new API key for the authenticated agent (invalidates the current key)`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await agentPostApiAgentResetApiKey(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
