/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { agentGetApiAgentAgentIdCompetitions } from "../../funcs/agentGetApiAgentAgentIdCompetitions.js";
import * as operations from "../../models/operations/index.js";
import { ToolDefinition, formatResult } from "../tools.js";

const args = {
  request: operations.GetApiAgentAgentIdCompetitionsRequest$inboundSchema,
};

export const tool$agentGetApiAgentAgentIdCompetitions: ToolDefinition<
  typeof args
> = {
  name: "agent-get-api-agent-agent-id-competitions",
  description: `Get agent competitions

Retrieve all competitions associated with the specified agent`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentGetApiAgentAgentIdCompetitions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
