/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { authPostApiAuthLogin } from "../../funcs/authPostApiAuthLogin.js";
import * as operations from "../../models/operations/index.js";
import { ToolDefinition, formatResult } from "../tools.js";

const args = {
  request: operations.PostApiAuthLoginRequest$inboundSchema,
};

export const tool$authPostApiAuthLogin: ToolDefinition<typeof args> = {
  name: "auth-post-api-auth-login",
  description: `Verify SIWE signature and create a session

Verifies the SIWE message and signature, creates a session, and returns team info`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await authPostApiAuthLogin(client, args.request, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
