/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { competitionGetApiCompetitionsCompetitionIdAgents } from "../../funcs/competitionGetApiCompetitionsCompetitionIdAgents.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.GetApiCompetitionsCompetitionIdAgentsRequest$inboundSchema,
};

export const tool$competitionGetApiCompetitionsCompetitionIdAgents:
  ToolDefinition<typeof args> = {
    name: "competition-get-api-competitions-competition-id-agents",
    description: `Get agents participating in a competition

Get a list of all agents participating in a specific competition with their scores and positions`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await competitionGetApiCompetitionsCompetitionIdAgents(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
