/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { emailVerificationGetApiVerifyEmail } from "../../funcs/emailVerificationGetApiVerifyEmail.js";
import * as operations from "../../models/operations/index.js";
import { ToolDefinition, formatResult } from "../tools.js";

const args = {
  request: operations.GetApiVerifyEmailRequest$inboundSchema,
};

export const tool$emailVerificationGetApiVerifyEmail: ToolDefinition<
  typeof args
> = {
  name: "email-verification-get-api-verify-email",
  description: `Verify an email verification token

Verifies an email verification token sent to a user or agent's email address.
This endpoint is typically accessed via a link in the verification email.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await emailVerificationGetApiVerifyEmail(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
