/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { healthGetApiHealthDetailed } from "../../funcs/healthGetApiHealthDetailed.js";
import { ToolDefinition, formatResult } from "../tools.js";

export const tool$healthGetApiHealthDetailed: ToolDefinition = {
  name: "health-get-api-health-detailed",
  description: `Detailed health check

Check if the API and all its services are running properly`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await healthGetApiHealthDetailed(client, {
      fetchOptions: { signal: ctx.signal },
    }).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
