/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { leaderboardGetApiLeaderboard } from "../../funcs/leaderboardGetApiLeaderboard.js";
import * as operations from "../../models/operations/index.js";
import { ToolDefinition, formatResult } from "../tools.js";

const args = {
  request: operations.GetApiLeaderboardRequest$inboundSchema,
};

export const tool$leaderboardGetApiLeaderboard: ToolDefinition<typeof args> = {
  name: "leaderboard-get-api-leaderboard",
  description: `Get global leaderboard

Get global leaderboard data across all relevant competitions`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await leaderboardGetApiLeaderboard(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
