/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tradeGetApiTradeQuote } from "../../funcs/tradeGetApiTradeQuote.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiTradeQuoteRequest$inboundSchema,
};

export const tool$tradeGetApiTradeQuote: ToolDefinition<typeof args> = {
  name: "trade-get-api-trade-quote",
  description: `Get a quote for a trade

Get a quote for a potential trade between two tokens`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tradeGetApiTradeQuote(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
