/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminGetTeams } from "../funcs/adminGetTeams.js";
import { adminSetup } from "../funcs/adminSetup.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { AdminCompetition } from "./admincompetition.js";
import { AdminTeams } from "./adminteams.js";
import { Reports } from "./reports.js";

export class Admin extends ClientSDK {
  private _teams?: AdminTeams;
  get teams(): AdminTeams {
    return (this._teams ??= new AdminTeams(this._options));
  }

  private _competition?: AdminCompetition;
  get competition(): AdminCompetition {
    return (this._competition ??= new AdminCompetition(this._options));
  }

  private _reports?: Reports;
  get reports(): Reports {
    return (this._reports ??= new Reports(this._options));
  }

  /**
   * Set up initial admin account
   *
   * @remarks
   * Creates the first admin account. This endpoint is only available when no admin exists in the system.
   */
  async setup(
    request: operations.PostApiAdminSetupRequest,
    options?: RequestOptions,
  ): Promise<operations.PostApiAdminSetupResponse> {
    return unwrapAsync(adminSetup(
      this,
      request,
      options,
    ));
  }

  /**
   * List all teams
   *
   * @remarks
   * Get a list of all non-admin teams
   */
  async getTeams(
    options?: RequestOptions,
  ): Promise<operations.GetApiAdminTeamsResponse> {
    return unwrapAsync(adminGetTeams(
      this,
      options,
    ));
  }
}
