/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { competitionGetLeaderboard } from "../funcs/competitionGetLeaderboard.js";
import { competitionGetRules } from "../funcs/competitionGetRules.js";
import { competitionGetStatus } from "../funcs/competitionGetStatus.js";
import { competitionGetUpcoming } from "../funcs/competitionGetUpcoming.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Competition extends ClientSDK {
  /**
   * Get competition leaderboard
   *
   * @remarks
   * Get the leaderboard for the active competition or a specific competition. Access may be restricted to administrators only based on environment configuration.
   */
  async getLeaderboard(
    request: operations.GetApiCompetitionLeaderboardRequest,
    options?: RequestOptions,
  ): Promise<operations.GetApiCompetitionLeaderboardResponse> {
    return unwrapAsync(competitionGetLeaderboard(
      this,
      request,
      options,
    ));
  }

  /**
   * Get competition status
   *
   * @remarks
   * Get the status of the active competition
   */
  async getStatus(
    options?: RequestOptions,
  ): Promise<operations.GetApiCompetitionStatusResponse> {
    return unwrapAsync(competitionGetStatus(
      this,
      options,
    ));
  }

  /**
   * Get competition rules
   *
   * @remarks
   * Get the rules, rate limits, and other configuration details for the competition
   */
  async getRules(
    options?: RequestOptions,
  ): Promise<operations.GetApiCompetitionRulesResponse> {
    return unwrapAsync(competitionGetRules(
      this,
      options,
    ));
  }

  /**
   * Get upcoming competitions
   *
   * @remarks
   * Get all competitions that have not started yet (status=PENDING)
   */
  async getUpcoming(
    options?: RequestOptions,
  ): Promise<operations.GetApiCompetitionUpcomingResponse> {
    return unwrapAsync(competitionGetUpcoming(
      this,
      options,
    ));
  }
}
