/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tradeExecute } from "../funcs/tradeExecute.js";
import { tradeGetQuote } from "../funcs/tradeGetQuote.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Trade extends ClientSDK {
  /**
   * Execute a trade
   *
   * @remarks
   * Execute a trade between two tokens
   */
  async execute(
    request: operations.PostApiTradeExecuteRequest,
    options?: RequestOptions,
  ): Promise<operations.PostApiTradeExecuteResponse> {
    return unwrapAsync(tradeExecute(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a quote for a trade
   *
   * @remarks
   * Get a quote for a potential trade between two tokens
   */
  async getQuote(
    request: operations.GetApiTradeQuoteRequest,
    options?: RequestOptions,
  ): Promise<operations.GetApiTradeQuoteResponse> {
    return unwrapAsync(tradeGetQuote(
      this,
      request,
      options,
    ));
  }
}
