global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "js-recall-api"
    static_configs:
      - targets: ["host.docker.internal:3000"]
    metrics_path: "/api/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/bearer_token.txt

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
