workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
  Trading Simulator API:
    inputs:
      - location: ../../apps/api/openapi/openapi.json
    registry:
      location: registry.speakeasyapi.dev/textile/recall-comp-api/trading-simulator-api
targets:
  api-sdk:
    target: typescript
    source: Trading Simulator API
    codeSamples:
      registry:
        location: registry.speakeasyapi.dev/textile/recall-comp-api/trading-simulator-api-typescript-code-samples
      labelOverride:
        fixedValue: Typescript (SDK)
      blocking: false
