"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubnetRegistryDiamond__factory = exports.SubnetActorDiamond__factory = exports.OwnershipFacet__factory = exports.GatewayDiamond__factory = exports.subnetregistry = exports.subnet = exports.lib = exports.interfaces = exports.gateway = exports.diamond = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.diamond = __importStar(require("./diamond"));
exports.gateway = __importStar(require("./gateway"));
exports.interfaces = __importStar(require("./interfaces"));
exports.lib = __importStar(require("./lib"));
exports.subnet = __importStar(require("./subnet"));
exports.subnetregistry = __importStar(require("./subnetregistry"));
var GatewayDiamond__factory_1 = require("./GatewayDiamond__factory");
Object.defineProperty(exports, "GatewayDiamond__factory", { enumerable: true, get: function () { return GatewayDiamond__factory_1.GatewayDiamond__factory; } });
var OwnershipFacet__factory_1 = require("./OwnershipFacet__factory");
Object.defineProperty(exports, "OwnershipFacet__factory", { enumerable: true, get: function () { return OwnershipFacet__factory_1.OwnershipFacet__factory; } });
var SubnetActorDiamond__factory_1 = require("./SubnetActorDiamond__factory");
Object.defineProperty(exports, "SubnetActorDiamond__factory", { enumerable: true, get: function () { return SubnetActorDiamond__factory_1.SubnetActorDiamond__factory; } });
var SubnetRegistryDiamond__factory_1 = require("./SubnetRegistryDiamond__factory");
Object.defineProperty(exports, "SubnetRegistryDiamond__factory", { enumerable: true, get: function () { return SubnetRegistryDiamond__factory_1.SubnetRegistryDiamond__factory; } });
//# sourceMappingURL=index.js.map