export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
export const ENABLE_SANDBOX = !!process.env.NEXT_PUBLIC_SANDBOX_API_URL;
export const SANDBOX_API_URL = process.env.NEXT_PUBLIC_SANDBOX_API_URL;
export const HAS_SANDBOX_ADMIN_KEY = !!process.env.SANDBOX_ADMIN_API_KEY;
export const SANDBOX_FULLY_CONFIGURED = ENABLE_SANDBOX && HAS_SANDBOX_ADMIN_KEY;
