services:
  # Application service
  app:
    build:
      context: ../../..
      dockerfile: apps/api/trade-simulator-docker/Dockerfile
    container_name: trading-simulator-app
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-3000}:3000"
    # Load all environment variables from .env file
    env_file:
      - ../.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1:${PORT:-3000}/api/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
