name: Load Tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-load-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-script: [test:agent-trading, test:users-api]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        working-directory: packages/load-test
        run: |
          echo "API_HOST=${{ secrets.API_URL }}" >> .env
          echo "ADMIN_API_KEY=${{ secrets.ADMIN_API_KEY }}" >> .env
          echo "AGENTS_COUNT=50" >> .env
          echo "TRADES_COUNT=100" >> .env
          echo "USERS_COUNT=2000" >> .env

      - name: Run load test
        run: pnpm --filter @recallnet/load-test ${{ matrix.test-script }}

      - name: Generate HTML report for agent-trading
        if: matrix.test-script == 'test:agent-trading'
        run: pnpm --filter @recallnet/load-test report:agent-trading

      - name: Generate HTML report for users-api
        if: matrix.test-script == 'test:users-api'
        run: pnpm --filter @recallnet/load-test report:users-api

      - name: Upload agent-trading report
        if: matrix.test-script == 'test:agent-trading'
        uses: actions/upload-artifact@v4
        with:
          name: load-test-report-agent-trading
          path: packages/load-test/reports/agent-trading.html

      - name: Upload users-api report
        if: matrix.test-script == 'test:users-api'
        uses: actions/upload-artifact@v4
        with:
          name: load-test-report-users-api
          path: packages/load-test/reports/users-api.html
