name: Agent Trading Load Tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-agent-trading-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        working-directory: packages/load-test
        run: |
          echo "API_HOST=${{ secrets.API_URL }}" >> .env
          echo "ADMIN_API_KEY=${{ secrets.ADMIN_API_KEY }}" >> .env
          echo "AGENTS_COUNT=50" >> .env
          echo "TRADES_COUNT=100" >> .env

      - name: Run agent trading load test
        run: pnpm --filter @recallnet/load-test test:agent-trading

      - name: Generate HTML report
        run: pnpm --filter @recallnet/load-test report:agent-trading

      - name: Upload agent trading report
        uses: actions/upload-artifact@v4
        with:
          name: load-test-report-agent-trading
          path: packages/load-test/reports/agent-trading.html
