# Creates version PR upon changeset updates merging into main
name: Version

on:
  push:
    paths:
      - ".changeset/**"
    branches:
      - main

env:
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: fe319abf1a1b0d76b39894e5e17aff0c
  NEXT_PUBLIC_CHAIN_NAME: testnet

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm version
          commit: "chore: version packages"
          title: "chore: version packages"
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
